import type { ChordKind } from './chordKinds';
import type { NoteName } from './noteUtils';

export const MUTED_OFFSET = -999;

export type ShapePattern = {
  str: number;
  fretOffset: number;
};

export type ShapeForm = {
  id: string;
  label: string;
  chordKind: ChordKind;
  rootString: 1 | 2 | 3 | 4 | 5 | 6;
  pattern: ShapePattern[];
  movable: boolean;
  referenceRoot: NoteName;
  referenceRootFret: number;
  muted?: number[];
  openStrings?: number[];
  minRootFret?: number;
  maxRootFret?: number;
  priority?: number;
  source?: string;
};

const REF = 'docs/reference_docs/guitar-chord-chart.png';

const open = (form: ShapeForm): ShapeForm => form;
const movable = (form: ShapeForm): ShapeForm => form;

export const SHAPE_FORMS: ShapeForm[] = [
  // Open major chords
  open({
    id: 'open-c-maj',
    label: 'Open C',
    chordKind: '',
    rootString: 5,
    referenceRoot: 'C',
    referenceRootFret: 3,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: -1 },
      { str: 3, fretOffset: -3 },
      { str: 2, fretOffset: -2 },
      { str: 1, fretOffset: -3 },
    ],
    muted: [6],
    source: `${REF}#C`,
  }),
  open({
    id: 'open-a-maj',
    label: 'Open A',
    chordKind: '',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: `${REF}#A`,
  }),
  open({
    id: 'open-g-maj',
    label: 'Open G',
    chordKind: '',
    rootString: 6,
    referenceRoot: 'G',
    referenceRootFret: 3,
    movable: false,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: -1 },
      { str: 4, fretOffset: -3 },
      { str: 3, fretOffset: -3 },
      { str: 2, fretOffset: -3 },
      { str: 1, fretOffset: 0 },
    ],
    source: `${REF}#G`,
  }),
  open({
    id: 'open-e-maj',
    label: 'Open E',
    chordKind: '',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    source: `${REF}#E`,
  }),
  open({
    id: 'open-d-maj',
    label: 'Open D',
    chordKind: '',
    rootString: 4,
    referenceRoot: 'D',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 3 },
      { str: 1, fretOffset: 2 },
    ],
    muted: [6, 5],
    source: `${REF}#D`,
  }),
  // Open minors
  open({
    id: 'open-a-minor',
    label: 'Open Am',
    chordKind: 'm',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 1 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: `${REF}#Am`,
  }),
  open({
    id: 'open-d-minor',
    label: 'Open Dm',
    chordKind: 'm',
    rootString: 4,
    referenceRoot: 'D',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 3 },
      { str: 1, fretOffset: 1 },
    ],
    muted: [6, 5],
    source: `${REF}#Dm`,
  }),
  open({
    id: 'open-dm7',
    label: 'Open Dm7',
    chordKind: 'm7',
    rootString: 4,
    referenceRoot: 'D',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 1 },
      { str: 1, fretOffset: 1 },
    ],
    muted: [6, 5],
    source: `${REF}#Dm7`,
  }),
  open({
    id: 'open-e-minor',
    label: 'Open Em',
    chordKind: 'm',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    source: `${REF}#Em`,
  }),
  // Open sevenths
  open({
    id: 'open-a7',
    label: 'Open A7',
    chordKind: '7',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: `${REF}#A7`,
  }),
  open({
    id: 'open-d7',
    label: 'Open D7',
    chordKind: '7',
    rootString: 4,
    referenceRoot: 'D',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 1 },
      { str: 1, fretOffset: 2 },
    ],
    muted: [6, 5],
    source: `${REF}#D7`,
  }),
  open({
    id: 'open-e7',
    label: 'Open E7',
    chordKind: '7',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    source: `${REF}#E7`,
  }),
  open({
    id: 'open-g7',
    label: 'Open G7',
    chordKind: '7',
    rootString: 6,
    referenceRoot: 'G',
    referenceRootFret: 3,
    movable: false,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: -1 },
      { str: 4, fretOffset: -3 },
      { str: 3, fretOffset: -3 },
      { str: 2, fretOffset: -3 },
      { str: 1, fretOffset: -2 },
    ],
    source: `${REF}#G7`,
  }),
  // Open maj7
  open({
    id: 'open-cmaj7',
    label: 'Open Cmaj7',
    chordKind: 'maj7',
    rootString: 5,
    referenceRoot: 'C',
    referenceRootFret: 3,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: -1 },
      { str: 3, fretOffset: -3 },
      { str: 2, fretOffset: -3 },
      { str: 1, fretOffset: -3 },
    ],
    muted: [6],
    source: `${REF}#Cmaj7`,
  }),
  open({
    id: 'open-gmaj7',
    label: 'Open Gmaj7',
    chordKind: 'maj7',
    rootString: 6,
    referenceRoot: 'G',
    referenceRootFret: 3,
    movable: false,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: -1 },
      { str: 4, fretOffset: -3 },
      { str: 3, fretOffset: -2 },
      { str: 2, fretOffset: -3 },
      { str: 1, fretOffset: -2 },
    ],
    source: `${REF}#Gmaj7`,
  }),
  open({
    id: 'open-fmaj7',
    label: 'Open Fmaj7',
    chordKind: 'maj7',
    rootString: 4,
    referenceRoot: 'F',
    referenceRootFret: 3,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: -1 },
      { str: 2, fretOffset: -2 },
      { str: 1, fretOffset: -3 },
    ],
    muted: [6],
    source: `${REF}#Fmaj7`,
  }),
  // Open sus chords
  open({
    id: 'open-dsus4',
    label: 'Dsus4',
    chordKind: 'sus',
    rootString: 4,
    referenceRoot: 'D',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 3 },
      { str: 1, fretOffset: 3 },
    ],
    muted: [6, 5],
    source: `${REF}#Dsus`,
  }),
  open({
    id: 'open-dsus2',
    label: 'Dsus2',
    chordKind: 'sus2',
    rootString: 4,
    referenceRoot: 'D',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 2 },
    ],
    muted: [6, 5],
    source: `${REF}#Dsus2`,
  }),
  open({
    id: 'open-asus2',
    label: 'Asus2',
    chordKind: 'sus2',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: `${REF}#Asus2`,
  }),
  open({
    id: 'open-asus4',
    label: 'Asus4',
    chordKind: 'sus',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: false,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 3 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: `${REF}#Asus`,
  }),
  // Movable E-root shapes
  movable({
    id: 'e-shape-maj',
    label: 'E shape barre',
    chordKind: '',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    priority: 2,
    source: 'caged-e-maj',
  }),
  movable({
    id: 'e-shape-min',
    label: 'Em shape barre',
    chordKind: 'm',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    priority: 2,
    source: 'caged-e-min',
  }),
  movable({
    id: 'e-shape-6',
    label: 'E shape 6',
    chordKind: '6',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 0 },
    ],
    source: 'caged-e6',
  }),
  movable({
    id: 'e-shape-m6',
    label: 'Em shape 6',
    chordKind: 'm6',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 0 },
    ],
    source: 'caged-em6',
  }),
  movable({
    id: 'e-shape-maj7',
    label: 'E shape maj7',
    chordKind: 'maj7',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 1 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    source: 'caged-e-maj7',
  }),
  movable({
    id: 'e-shape-m7',
    label: 'Em shape 7',
    chordKind: 'm7',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: 2 },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    source: 'caged-em7',
  }),
  movable({
    id: 'e-shape-7-shell',
    label: '6th string 7 shell',
    chordKind: '7',
    rootString: 6,
    referenceRoot: 'E',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: -1 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: MUTED_OFFSET },
    ],
    muted: [5, 1],
    source: 'shell-7',
  }),
  movable({
    id: 'e-shape-9',
    label: '6th string 9',
    chordKind: '9',
    rootString: 6,
    referenceRoot: 'G',
    referenceRootFret: 3,
    movable: true,
    minRootFret: 1,
    pattern: [
      { str: 6, fretOffset: 0 },
      { str: 5, fretOffset: MUTED_OFFSET },
      { str: 4, fretOffset: 0 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 2 },
    ],
    muted: [5],
    source: 'g9-shell',
  }),
  // Movable A root
  movable({
    id: 'a-shape-maj',
    label: 'A shape barre',
    chordKind: '',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'caged-a-maj',
  }),
  movable({
    id: 'a-shape-min',
    label: 'Am shape barre',
    chordKind: 'm',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 1 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'caged-a-min',
  }),
  movable({
    id: 'a-shape-7',
    label: 'A shape 7',
    chordKind: '7',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'caged-a7',
  }),
  movable({
    id: 'a-shape-m7',
    label: 'A shape m7',
    chordKind: 'm7',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: 1 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'caged-am7',
  }),
  movable({
    id: 'a-shape-maj7',
    label: 'A shape maj7',
    chordKind: 'maj7',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'caged-amaj7',
  }),
  movable({
    id: 'a-shape-6',
    label: 'A shape 6',
    chordKind: '6',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 2 },
      { str: 1, fretOffset: 2 },
    ],
    muted: [6],
    source: 'caged-a6',
  }),
  movable({
    id: 'a-shape-m6',
    label: 'A shape m6',
    chordKind: 'm6',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 1 },
      { str: 1, fretOffset: 2 },
    ],
    muted: [6],
    source: 'caged-am6',
  }),
  movable({
    id: 'a-shape-m9',
    label: 'A string m9',
    chordKind: 'm9',
    rootString: 5,
    referenceRoot: 'C',
    referenceRootFret: 3,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: -2 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: -2 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'drop2-m9',
  }),
  movable({
    id: 'a-shape-maj9',
    label: 'A string maj9',
    chordKind: 'maj9',
    rootString: 5,
    referenceRoot: 'C',
    referenceRootFret: 3,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: -1 },
      { str: 3, fretOffset: 0 },
      { str: 2, fretOffset: -1 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'drop2-maj9',
  }),
  movable({
    id: 'a-shape-sus4',
    label: 'A string sus4',
    chordKind: 'sus',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 3 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'caged-a-sus',
  }),
  movable({
    id: 'a-shape-sus2',
    label: 'A string sus2',
    chordKind: 'sus2',
    rootString: 5,
    referenceRoot: 'A',
    referenceRootFret: 0,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 2 },
      { str: 3, fretOffset: 2 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: 0 },
    ],
    muted: [6],
    source: 'caged-a-sus2',
  }),
  // Specialty voicings
  movable({
    id: 'a-shape-dim',
    label: 'A string diminished',
    chordKind: 'dim',
    rootString: 5,
    referenceRoot: 'B',
    referenceRootFret: 2,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 1 },
      { str: 3, fretOffset: -1 },
      { str: 2, fretOffset: 1 },
      { str: 1, fretOffset: -1 },
    ],
    muted: [6],
    source: `${REF}#Bdim`,
  }),
  movable({
    id: 'top4-aug',
    label: 'Augmented grip',
    chordKind: 'aug',
    rootString: 5,
    referenceRoot: 'C',
    referenceRootFret: 3,
    movable: true,
    pattern: [
      { str: 6, fretOffset: MUTED_OFFSET },
      { str: 5, fretOffset: 0 },
      { str: 4, fretOffset: 1 },
      { str: 3, fretOffset: 1 },
      { str: 2, fretOffset: 0 },
      { str: 1, fretOffset: MUTED_OFFSET },
    ],
    muted: [6, 1],
    source: 'jazz-aug',
  }),
];

export function getFormsForKind(kind: ChordKind): ShapeForm[] {
  return SHAPE_FORMS.filter((form) => form.chordKind === kind);
}
